name: secret value

on: [workflow_dispatch] 

env:
  ## Sets environment variable
  
  
  EMAIL: ${{secrets.EMAIL}}    
  PASSWORD: ${{secrets.PASSWORD}}
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i  
      - name: Run test script
        run: npm run test
